# Generated by Django 3.2.8 on 2021-10-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematable',
            name='column_separator',
            field=models.CharField(default=',', max_length=2),
        ),
        migrations.AddField(
            model_name='schematable',
            name='string_character',
            field=models.CharField(default='"', max_length=2),
        ),
    ]
