# Generated by Django 3.2.8 on 2021-10-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211028_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='range_lower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='range_upper',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='schemafield',
            unique_together={('schema_table', 'order')},
        ),
    ]
