# Generated by Django 3.2.8 on 2021-10-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211028_1617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schemafield',
            unique_together={('schema_table', 'order'), ('schema_table', 'name')},
        ),
    ]
