# Generated by Django 3.2.8 on 2021-10-28 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_schemafield_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='schema_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.schematable'),
        ),
    ]
