# Generated by Django 3.2.8 on 2021-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_schemadata_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='type',
            field=models.CharField(choices=[('Full name', 'Full name'), ('Email', 'Email'), ('Phone number', 'Phone number'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], max_length=20),
        ),
    ]
